project:
  type: book
  output-dir: docs

execute:
  freeze: auto

book:
  title: "A cognitive perspective on trust in science (PhD thesis)"
  author: "Jan Pfänder"
  date: "4/15/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - consensus_trust/consensus_trust.qmd
    - everyone_trusts_science_abit/everyone_trusts_science_abit.qmd
    - references.qmd
  search: true
  repo-url: https://github.com/jjallaire/hopr/
  repo-actions: [edit]
  downloads: [pdf, epub]

bibliography: 
  - references.bib # the intro and discussion references
  - consensus_trust/references.bib  
  - everyone_trusts_science_abit/references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



