# Acknowledgements {.unnumbered}

There are many wonderful people in my life who made writing this thesis possible. 

First and foremost, I have to thank my supervisor, Hugo Mercier. Without Hugo, I would never have been able to write this thesis—nor would I have started any thesis in the first place. When he agreed to supervise me as an intern during my Master’s, I was completely new to cognitive science and completely clueless. What followed were one and a half years of failed experiments on a topic we never returned to. And yet, somehow, Hugo made this experience fun and intellectually stimulating. More than that, he gave me the feeling that my thoughts mattered. Hugo always made time for me, whether in weekly meetings or within-the-minute replies to my emails. I would never have imagined myself as a researcher if it weren’t for Hugo’s kindness, generosity, and encouragement. I still have a lot to learn from him, and I hope we’ll have many opportunities to keep working together in the future.

I thank Sacha Altay, who is not only a friend but has also been an academic mentor to me. Sacha’s down-to-earth attitude while producing great research is a constant inspiration. He also taught me to be more pragmatic (though I still have a long way to go).

I’ve been fortunate to be part of a team of brilliant and kind people at the Institut Jean Nicod. I couldn’t have hoped for a more intellectually stimulating place to grow up, academically speaking. I’m grateful for the fun conversations, the valuable feedback, and the delicious pizza after lab meetings. In particular, I’d like to thank my co-authors Benoît, Sophie, and Lou for their excellent collaboration. I also have to single out Coralie Chevalier, who’s class on psychology and public policy first inspired me to apply for a Master’s in Cognitive Science. I’m also grateful for her trust in giving me the opportunity to design and teach my own course.

Thanks to Lilas, for being a great friend, faithful lunch companion, and making sure I didn’t miss countless administrative requirements and deadlines.

I was incredibly lucky to have made many friends in Paris who helped take my mind off research when needed, in particular Amelie, Elie, Edgar, Simon and Fiona. I also want to thank all the amazing people I was lucky enough to play music with--Adrian, Daniel, Enora, Luis, Bella, Chippy, Kenta, Malin, Michael, Octave, Rémy, Pablo, Marina, Reynaldo. These sessions and concerts always lifted me up, no matter how frustrating the day had been.

The two people who made Paris feel like home are my flatmates, Enara and Adrian. I owe much of my sanity and my sense of belonging in Paris to them. Lazy TV nights with ice cream-induced stomachaches or concerts in squads--with them, any plan is a good plan. Over the last couple of years, I’ve spent more time with Adrian than with anyone else, and I’ve cherished every single moment. This is what I will most miss about Paris.

There are other friends who, despite the distance, are always present in my life. Leon, Pauli, Jonas, Luis, Jakob, Chris, Eva, and Basti have been around for as long as I can remember, and they mean the world to me. There are also my dear friends Joseph and Sylvie who I wish I would see more often.

I would like to thank my parents, who love me and always trust me to do the right thing. Neither of them got a university degree, yet they unconditionally supported me through all those years of education. I thank my dad, Thorsten, who always inspired me to think critically. I look up to him for his unshakable optimism and stamina. I thank my mum, Katja, for putting me on the right track in so many ways: for making me learn an instrument, for the countless hours she spent reading to me as a child, for helping me study vocabulary, for running a household with four kids while working. I’m incredibly grateful to have my siblings Luca, Jona, and Franca in my life, and for the moments of laughter and empathy we share whenever we’re all home together.

Thanks to my grandma, Oma Brunhilde, for being living proof that people who occasionally distrust science can be the loveliest people. Thanks to Opa Erwin, for always taking care of us. And to Oma Renate and to Opa Horst, who never got tired of sharing his passion for history with me and would probably have been the single most proud person to see me finish a dissertation.

I was fortunate enough to have been adopted by a second family in Spain. I thank Consu and Miguel for their endless generosity and for giving me a sense of calm I’ve never experienced anywhere else. Thanks to Maria and Dani for always supporting me. 

I owe special thanks to Carmen, for never getting tired of showing me all that is beautiful in life. I may have found more insight in the novels that she has offered me over the years than I could ever find in research. 

